select 
       APEX_ITEM.CHECKBOX(01,ID, NULL,2 ,NULL,'NOEM') AS CHECKB
from GC_CURSO_DESEJADO

DECLARE
v_ID_ALUNO NUMBER;
BEGIN
INSERT INTO GC_ALUNOS (
       NOME_ALUNOS,
) VALUES (
    :P11_NOME_ALUNOS
)RETURNING ID_ALUNOS INTO v_ID_ALUNO;

FOR I IN 1..APEX_APPLICATION.G_F01.COUNT LOOP
    INSERT INTO GC_CURSO_DESEJADO(
        FK_CURSO,
        FK_ALUNO
    ) VALUES (
        APEX_APPLICATION.G_F01(I),
        v_ID_ALUNO
    );
    END LOOP;
END;
